### ISSUE TITLE
Seaweed no longer grows and crashes game after broken

### ISSUE THREAD

**Issue by Lexingtondavid** [91loocekaj/vs-wildfarming#2]
VS version 1.15.10
WildFarming version 1.0.3

Hovering over the seaweed displays that it no longer has any growth time at all in the tool tip, and breaking the seaweed with anything at all crashes the game after a second.

Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.10 (Stable)2022-01-03 12:10:20 AM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at WildFarming.BESeaweed.growthMonitior(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _37NyQC3j7xjnAt2h09BqVJtTM8J._Gd91jD2RZpLWue9im8O82g8B3Mn(Single )
   at _R2SaBRGSTE9aIRQAjhFb2LrMpJb._gq2ZjDtIZ3sLq4OCUiRUzkjv3XA(Single )
   at _R2SaBRGSTE9aIRQAjhFb2LrMpJb._tjdmYyEuuoCShcgREvOOHIl2K1G(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _rwEcecUjMyzMSfVPsyS8Wx2kGqk._XiZO0qHpODOJko3v6YCZBF7Z5Se(_2kddpZuU7wcyt2belKg18dkvHxo , String[] )
   at _E5WqgB878qvAOVUQ9yfqu340l7G._XiZO0qHpODOJko3v6YCZBF7Z5Se(ThreadStart )
-------------------------------

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2021-12-24 11:10:45 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2031197943922000226, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.10.0
P3: 10.0.19043.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\dylan\AppData\Local\Temp\RDR9DED.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9DFE.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9E0E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9E3B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9E5B.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4b5bd439-a6cb-44db-a4fd-1518c051cd22
Report Status: 268435456
Hashed bucket: 9abb75f1824b165bdc3043c4abf98162
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-12-22 6:51:07 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: AppHangTransient
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.10.0
P3: 61a0f259
P4: unknown
P5: unknown
P6: unknown
P7: unknown
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER329C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER32DB.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER32DA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER330A.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 09b466bd-ec1c-40bd-91b8-cbf63b587305
Report Status: 2049
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 2021-12-18 5:36:07 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1449690627887415421, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.15.10.0
P3: 61a0f259
P4: KERNELBASE.dll
P5: 10.0.19041.1348
P6: 76fcd692
P7: c000041d
P8: 0000000000034f69
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1090.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1285.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1296.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1298.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER12C8.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_8081b6513db4e0ce367a8ed327bd2342feb2648_fc74ddd9_0ded8f0b-f049-486b-b7c8-bb896ec672c4

Analysis symbol: 
Rechecking for solution: 0
Report Id: f7833141-05ce-45e4-aaf8-d0d80905c7b8
Report Status: 268435456
Hashed bucket: e3202570f18df7e2041e55f1fd71407d
Cab Guid: 0 
[client-debug.txt](https://github.com/91loocekaj/vs-wildfarming/files/7800513/client-debug.txt)
}

**Comment by 91loocekaj** [comment]
This should be fixed in latest version
