### ISSUE TITLE
Too many termite mounds

### ISSUE THREAD

**Issue by dann1kid** [91loocekaj/vs-wildfarming#3]
![image](https://user-images.githubusercontent.com/40342734/152822845-a71d4efe-cd81-4e56-bd21-8c9152f53762.png)
i added time (-> 500 years) , maybe it makes this, but...

**Comment by 91loocekaj** [comment]
Termite mounds also reproduce themselves as they eat away from trees and kill saplings, that is why they are all hugging the trees and the borders where saplings would grow. The more trees around, the more food they have to grow and multiply. But I am releasing a hotfix to reduce the chance trees spawn them around.

**Comment by 91loocekaj** [comment]
Has been reduced by 5 times
