### ISSUE TITLE
Some ticks take long time

### ISSUE THREAD

**Issue by dann1kid** [91loocekaj/vs-wildfarming#4]
Just note for optimization, if you can fix it. Last updates was nice

10.2.2022 13:44:34 [Notification] A tick took 162,02ms
gmlewildcraft.BlockEntityWCBerryBush: 135,66ms
entity-done-bh-repulseagents: 3,75ms
entity-controlledphysics-end: 3,68ms
entity-done-bh-timeddespawn: 2,5ms
gmleVintagestory.GameContent.EntityPartitioning: 1,72ms
entity-done-bh-controlledentityphysics: 1,17ms
gmleVintagestory.GameContent.BlockEntityFirepit: 1,12ms
entity-done-bh-floatupwhenstuck: ,7ms

10.2.2022 13:44:34 [Notification] A tick took 161,47ms
gmlewildcraft.BlockEntityWCBerryBush: 113,89ms
gmleVintagestory.GameContent.EntityPartitioning: 17,78ms
entity-controlledphysics-end: 6,36ms
entity-done-bh-repulseagents: 3,89ms
gmleVintagestory.Server.ServerSystemEntitySpawner: 2,59ms
entity-done-bh-timeddespawn: 2,17ms
entity-done-bh-controlledentityphysics: 1,53ms
entity-done-bh-harvestable: 1,53ms

**Comment by 91loocekaj** [comment]
I do not add any bush entities, that one is from the Wildcraft mod: https://github.com/slightlycolorblind/Wildcraft/blob/main/wildcraft/src/BlockEntity/BlockEntityWCBerryBush.cs
