### ISSUE TITLE
Some grown trees don't completely chop with axe

### ISSUE THREAD

**Issue by RogueRaiden** [91loocekaj/vs-wildfarming#7]
Hello,
Seems some growing trees, at least pine so far, don't like to fully chop from axes. I'm not sure exactly if its leaves growing in place of logs or some logs not connecting all the way up. Been seeing a few floating tree tops around the server.

**Comment by 91loocekaj** [comment]
Just released an update for this. Trees should now be purely vanilla with update 1.3.0, so there should be no more issues, given the tree is chopped in the right position.
